global:
  scrape_interval: 15s # De quanto em quanto tempo ele vai buscar os dados

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sock-shop'
    static_configs:
      # Aqui dizemos ao Prometheus quais microserviços ele deve vigiar
      - targets: ['front-end:8079', 'catalogue:80', 'orders:80', 'payment:80', 'user:80']