input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => { "ambiente" => "sock-shop" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "sockshop-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}